---
title: "COBS(Constrained B-spline smoothing)"
author: "Soyeon Hwang, SDMLAB"
output:
  pdf_document:
    includes:
      in_header: Markdown.tex
    number_sections: yes
  html_document:
    df_print: paged
fontsize: 12pt
editor_options:
  chunk_output_type: console
---

loads
```{r, echo = TRUE, results = 'hide', warning=FALSE, message=FALSE, fig.align = 'center', fig.width = 6, fig.height = 6}
rm(list = ls())
library(cobs)
library(latex2exp)
library(Hmisc)
```

# generate dataset to test
```{r}
# make an indicator function
Ivec = function(x)
{
   1 * (x > 0)
}

# set the true function
X = seq(0, 1, length = 100)
f = X * Ivec(0.3 - X) + 1.5 * X * Ivec(X - 0.6) + 0.3 * Ivec(X - 0.3) + 2 * X * Ivec(X - 0.8)
set.seed(13)
Y = f + rnorm(n = length(X), sd = 0.2)
plot(X, Y, col = "grey", cex = 1.3, main = "true function and data")
lines(X, f, lwd = 2, col = "grey")
```

# apply COBS function
### define the number of knots 
```{r}
fit_cobs = cobs(X, Y, constraint = "increase", nknots = 99, degree = 2)
plot(X, Y, col = "grey", cex= 1.3)
lines(X, fit_cobs$fitted, col = "red", lwd = 2)

# the final knots
fit_cobs$knots 

# lambda value (lambda =0: regression B-spline)
fit_cobs$lambda 
```

### set different lambda values
```{r}
# cobs with lambda = 0.03
fit_cobs2 = cobs(X, Y, constraint = "increase", nknots = 99, degree = 2, 
                 lambda = 0.03)

# the final knots of fit_cobs2
fit_cobs2$knots

# cobs with lambda = 0.1
fit_cobs3 = cobs(X, Y, constraint = "increase", nknots = 99, degree = 2, 
                 lambda = 0.1)

# the final knots of fit_cobs3
fit_cobs3$knots

# comparison of the fits
plot(X, Y, col = "grey", cex= 1.3)
lines(X, fit_cobs$fitted, col = "black", lwd = 2)
lines(X, fit_cobs2$fitted, col = "red", lwd = 2)
lines(X, fit_cobs3$fitted, col = "blue", lwd = 2)
legend("topleft", legend = c(TeX("$ \\lambda = 0$"), TeX("$ \\lambda = 0.03$"), TeX("$ \\lambda = 0.1$")), lty = c(1, 1, 1), col = c("black", "blue", "red"))
```

